name: XeonInventory
version: ${project.version}.b${build.number}
description: SQL Inventory plugin for bungeecord
author: Kekshaus
main: de.linzn.xeonInventory.InventoryPlugin
commands:
   inv:
      description: Alle xeonInventory Commands
      usage: /<command>
      aliases: [cinv]
   fly:
      description: Alle xeonInventory Commands
      usage: /<command>
      aliases: [cfly]
   gm:
      description: Alle xeonInventory Commands
      usage: /<command>
      aliases: [gamemode, cgm]
   vanish:
      description: Alle xeonInventory Commands
      usage: /<command>
      aliases: [cvanish, v]
   give:
      description: Alle xeonInventory Commands
      usage: /<command>
   time:
      description: Alle xeonInventory Commands
      usage: /<command>
   weather:
      description: Alle xeonInventory Commands
      usage: /<command>
   clear:
      description: Alle xeonInventory Commands
      usage: /<command>
permissions:
    xeonInventory.team:
        description: Alle Permissions
        children:
            xeonInventory.default: true
            xeonInventory.team.fly: true
            xeonInventory.team.gamemode: true
            xeonInventory.team.gamemodeOther: true
            xeonInventory.team.vanish: true
            xeonInventory.team.give: true
            xeonInventory.team.time: true
            xeonInventory.team.weather: true
            xeonInventory.team.clear: true
    xeonInventory.default:
        description: Alle Permissions
        children:
            xeonInventory.cmd.help: true
            xeonInventory.cmd.load: true
    xeonInventory.cmd.help:
        description: help
        default: op
    xeonInventory.cmd.load:
        description: load
        default: op
    xeonInventory.team.fly:
        description: load
        default: op
    xeonInventory.team.gamemode:
        description: load
        default: op
    xeonInventory.team.gamemodeOther:
        description: load
        default: op
    xeonInventory.team.vanish:
        description: load
        default: op
    xeonInventory.team.weather:
        description: load
        default: op
    xeonInventory.team.time:
        description: load
        default: op
    xeonInventory.team.clear:
        description: load
        default: op
