name: MineProfile
version: ${project.version}
description: SQL Inventory plugin for bungeecord
author: Kekshaus
main: de.linzn.mineProfile.MineProfilePlugin
api-version: 1.13

commands:
   inv:
      description: Alle mineProfile Commands
      usage: /<command>
      aliases: [cinv]
   fly:
      description: Alle mineProfile Commands
      usage: /<command>
      aliases: [cfly]
   gm:
      description: Alle mineProfile Commands
      usage: /<command>
      aliases: [gamemode, cgm]
   vanish:
      description: Alle mineProfile Commands
      usage: /<command>
      aliases: [cvanish, v]
   give:
      description: Alle mineProfile Commands
      usage: /<command>
   time:
      description: Alle mineProfile Commands
      usage: /<command>
   weather:
      description: Alle mineProfile Commands
      usage: /<command>
   clear:
      description: Alle mineProfile Commands
      usage: /<command>
permissions:
    mineProfile.team:
        description: Alle Permissions
        children:
            mineProfile.default: true
            mineProfile.team.fly: true
            mineProfile.team.gamemode: true
            mineProfile.team.gamemodeOther: true
            mineProfile.team.vanish: true
            mineProfile.team.give: true
            mineProfile.team.time: true
            mineProfile.team.weather: true
            mineProfile.team.clear: true
    mineProfile.default:
        description: Alle Permissions
        children:
            mineProfile.cmd.help: true
            mineProfile.cmd.load: true
    mineProfile.cmd.help:
        description: help
        default: op
    mineProfile.cmd.load:
        description: load
        default: op
    mineProfile.team.fly:
        description: load
        default: op
    mineProfile.team.gamemode:
        description: load
        default: op
    mineProfile.team.gamemodeOther:
        description: load
        default: op
    mineProfile.team.vanish:
        description: load
        default: op
    mineProfile.team.weather:
        description: load
        default: op
    mineProfile.team.time:
        description: load
        default: op
    mineProfile.team.clear:
        description: load
        default: op
